DjangoChat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('rooms/', include('room.urls')),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import frontpage, signUp

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signUp, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

room/urls.py
from django.urls import path

from .views import rooms, room

app_name = 'room'

urlpatterns = [
    path('', rooms, name='rooms'),
    path('<slug:slug>/', room, name='room'),
]

core/models.py
from django.db import models

# Create your models here.

room/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    room = models.ForeignKey(
        Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'password1']

core/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect

from .forms import SignUpForm


def frontpage(request):
    return render(request, 'core/frontpage.html')


def signUp(request):
    if request.method == 'POST':

        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)
            return redirect('core:frontpage')
    else:
        form = SignUpForm()

    return render(request, 'core/signUp.html', {'form': form})


def loginPage(request):
    return render(request, 'core/login.html')

room/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Room, Message


@login_required
def rooms(request):
    rooms = Room.objects.all()
    return render(request, 'room/rooms.html', {'rooms': rooms})


@login_required
def room(request, slug):
    room = Room.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)[0:20]

    return render(request, 'room/room.html', {'room': room, 'messages': messages})

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %} DjangoChat</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        .chat-messages {
            height: 400px;
            overflow-y: auto;
        }
    </style>
</head>
<body class="bg-teal-500">
    <nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
        <div>
            <a href="#" class="text-xl text-white">Djangochat</a>
        </div>

        <div class="flex items-center space-x-2">
            {% if request.user.is_authenticated %}
            <a href="/rooms/" class="text-white hover:text-gray-200">Rooms</a>
            <a href="/logout/" class="px-4 py-3 rounded-xl text-white bg-teal-500 hover:bg-teal-700">Logout</a>
            {% else %}
            <a href="/login/" class="text-white hover:text-gray-200">Log in</a>
            <a href="/signup/" class="px-4 py-3 rounded-xl text-white bg-teal-500 hover:bg-teal-700">Sign Up</a>
            {% endif %}
        </div>
    </nav>

    {% block content %} {% endblock %}
    {% block scripts %} {% endblock %}
</body>
</body>
</html>

templates/core/frontpage.html
{% extends 'core/base.html' %}
{% block title %} Welcome | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Django Chat</h1>
</div>
{% endblock %}

templates/core/login.html
{%  extends 'core/base.html' %}
{% block title %} SignUp | {% endblock %}

{% block content %}

<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Sign Up</h1>
</div>

<form method="POST" action="." class="max-w-sm px-4 mx-auto w-full">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>
        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>
        <input type="password" placeholder="Enter Password" name="password" class=" w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
    {% for field in forms %}
    {% for error in field.errors %}
    <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
        <p>{{ error|escape }}</p>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    <button class="px-5 py-3 text-white rounded-xl bg-teal-800 hover:bg-teal-700">Submit</button>

</form>

{% endblock %}

templates/core/signUp.html
{%  extends 'core/base.html' %}
{% block title %} SignUp | {% endblock %}

{% block content %}

<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Sign Up</h1>
</div>

<form method="POST" action="." class="max-w-sm w-full px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>
        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>
        <input type="password" placeholder="Enter Password" name="password" class=" w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Repeat password</label>
        <input type="password" placeholder="Enter Password Again" name="password1"
            class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
    {% for field in forms %}
    {% for error in field.errors %}
    <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
        <p>{{ error|escape }}</p>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    <button class="px-5 py-3 text-white rounded-xl bg-teal-800 hover:bg-teal-700">Submit</button>

</form>

{% endblock %}

templates/room/room.html
{% extends 'core/base.html' %}
{% block title %} {{room.name}} | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl md:text-4xl lg:text-6xl text-white">{{room.name}}</h1>
</div>

<div class="lg:w-2/4 mx-auto lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
        {% for message in messages %}
        <div class="p-4 bg-gray-100 rounded-xl">
            <p class="font-semibold"> {{ message.user.username }}</p>
            <p> {{ message.content }} </p>
        </div>
        {% endfor %}
    </div>
</div>

<div class=" mt-5 mb-5 lg:w-2/4 mx-auto lg:mx-auto p-4 bg-white rounded-xl">
    <form method="POST" action="." class="flex">
        <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message.." id="chat-message-input">
        <button class="px-5 py-3 rounded-xl text-white bg-teal-500 hover:bg-teal-800"
            id="chat-message-submit">Submit</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
{{room.slug|json_script:'json_roomname'}}
{{request.user.username|json_script:'json_username'}}

<script type="text/javascript">

    const roomName = JSON.parse(document.getElementById('json_roomname').textContent);
    const userName = JSON.parse(document.getElementById('json_username').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onclose = function (e) {
        console.log('onclose');
    }

    chatSocket.onmessage = function (e) {

        const data = JSON.parse(e.data)

        if (data.message) {
            let html = '<div class="p-4 bg-gray-100 rounded-xl">';
            html += '<p class="font-semibold">' + data.username + '</p>';
            html += '<p>' + data.message + '</p></div>';

            document.querySelector('#chat-messages').innerHTML += html;

            scrollToBottom();
        } else {
            alert("The message was empty.")
        }

    }



    document.querySelector('#chat-message-submit').onclick = function (e) {
        e.preventDefault();

        const messageInputDom = document.querySelector('#chat-message-input')
        const message = messageInputDom.value;

        console.log({
            'message': message,
            'username': userName,
            'room': roomName
        })

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }))
        messageInputDom.value = ''
    }

    function scrollToBottom() {
        const objDiv = document.getElementById('chat-messages')
        objDiv.scrollTop = objDiv.scrollHeight
    }

    scrollToBottom();

</script>


{% endblock %}

templates/room/rooms.html
{% extends 'core/base.html' %}
{% block title %} Rooms | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl md:text-4xl lg:text-6xl text-white">Rooms</h1>
</div>

<div class="w-full flex flex-wrap items-center">
    {% for room in rooms %}
    <div class="w-full md:w-1/4 lg:w-1/4 px-3 py-3">
        <div class="p-4 bg-white shadow rounded-xl text-center">
            <h2 class="mb-5 text-2xl font-semibold">{{room.name}}</h2>
            <a href="{% url 'room:room' room.slug %}"
                class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-800">Join</a>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}